---
site_name: Keith Gaughan
copyright: "Keith Gaughan, 2020"

remote_branch: master

use_directory_urls: false

theme:
  name: mkdocs

markdown_extensions:
  - smarty
  - sane_lists

plugins: []

nav:
  - Home: index.md
  - About: about.md
